//
// Created by bele on 18.11.17.
//

#ifndef RADIOHEADSOCKET_ESP8266UDPSOCKET_H
#define RADIOHEADSOCKET_ESP8266UDPSOCKET_H


class ESP8266UDPSocket {
    // TODO implement me
};


#endif //RADIOHEADSOCKET_ESP8266UDPSOCKET_H
